version: "3.5"
services:
  sgcommander-homepage:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: sgcommander-homepage
    environment:
      - UNIVERSE_HOSTS=${UNIVERSE_HOSTS}
    volumes:
      - ./:/var/www
    ports:
      - "8888:80"
    networks:
      - sgcommander-network

networks:
  sgcommander-network:
    external: true